yourName = input("What is your name?")
favouriteFood = input("What is your favourite food?")
favouriteMusic = input("What is your favourite music?")
yourLocation = input("Where do you live?")

print("Getting to know you!")

print("You are")
print(yourName)
print()
print("You're probably hungry for")
print(favouriteFood)
print()
print("and you're definitely getting your groove on to")
print(favouriteMusic)
print()
print("living in the amazing")
print(yourLocation)
print()
print ("Have a great day!")